"""
Effective sample size, and cluster-robust intervals for what depends on it.

Every split in this benchmark is generated by instantiating a fixed chain
template with a name and a colour pair. Rows are therefore not independent
draws: `test_variant1.csv` has 1000 rows built from 30 distinct structures, one
per ordered colour pair, each repeated 33 times. Any statistic that treats
questions as independent overstates its precision by roughly the replication
factor.

This matters for the item-level figures in the paper. It does not affect the
seed-level comparisons, which are computed over training runs and are the right
unit for a claim about a method.

Two numbers are reported per split. The structural unique count strips the name,
which is a pure surface variable, and counts distinct (facts, rules) pairs. The
cluster-robust interval resamples whole structures rather than questions, so a
split with 30 structures gets an interval reflecting 30 independent units
however many rows it contains.
"""

import argparse
import csv
import glob
import json
import os
import re
import sys
from collections import defaultdict

NAMES = ["Anne", "Bob", "Claire", "David", "Emma", "Frank", "Grace", "Helen",
         "Ivan", "Julia", "Kevin", "Linda", "Mike", "Nancy", "Oscar"]
_NAME_RE = re.compile(r"\b(" + "|".join(NAMES) + r")\b")


def structure_key(facts, rules):
    """Identity of the instance with surface variables removed."""
    return (_NAME_RE.sub("_", facts), _NAME_RE.sub("_", rules))


def split_stats(path):
    rows = list(csv.DictReader(open(path, encoding="utf-8")))
    if not rows or "facts" not in rows[0]:
        return None
    verbatim = {(r["facts"], r["rules"]) for r in rows}
    struct = {structure_key(r["facts"], r["rules"]) for r in rows}
    nq = sum(len(r["answers"].split(" | ")) for r in rows)
    return {
        "rows": len(rows), "questions": nq,
        "unique_verbatim": len(verbatim), "unique_structures": len(struct),
        "replication": round(len(rows) / len(struct), 1),
        "effective_fraction": round(len(struct) / len(rows), 4),
    }


def cluster_bootstrap(pred_csv, split_csv, n_boot=2000, seed=0):
    """Resample structures, not questions.

    Returns the point estimate and a 95% interval whose width reflects the
    number of independent structures rather than the number of rows.
    """
    import random
    import statistics as st
    ref = {}
    for r in csv.DictReader(open(split_csv, encoding="utf-8")):
        ref[(r["group_id"], r["facts"])] = structure_key(r["facts"], r["rules"])
    by = defaultdict(list)
    n_unmatched = 0
    for r in csv.DictReader(open(pred_csv, encoding="utf-8")):
        k = ref.get((r["group_id"], r["facts"]))
        if k is None:
            n_unmatched += 1
            continue
        by[k].append(int(r["prediction"] == r["ground_truth"]))
    if not by:
        return None
    clusters = list(by.values())
    point = sum(sum(c) for c in clusters) / sum(len(c) for c in clusters)
    rng = random.Random(seed)
    boots = []
    for _ in range(n_boot):
        s = [clusters[rng.randrange(len(clusters))] for _ in clusters]
        tot = sum(len(c) for c in s)
        boots.append(sum(sum(c) for c in s) / tot if tot else 0.0)
    boots.sort()
    lo, hi = boots[int(0.025 * n_boot)], boots[int(0.975 * n_boot)]
    # the naive interval a question-level analysis would report, for contrast
    n = sum(len(c) for c in clusters)
    naive = 1.96 * (point * (1 - point) / n) ** 0.5
    return {"accuracy": round(point, 4), "clusters": len(clusters), "questions": n,
            "ci95_cluster": [round(lo, 4), round(hi, 4)],
            "ci95_naive": [round(point - naive, 4), round(point + naive, 4)],
            "width_ratio": round((hi - lo) / (2 * naive), 2) if naive else None,
            "unmatched_rows": n_unmatched}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="results/effective_sample_size.json")
    ap.add_argument("--checkpoints", nargs="*", default=[
        "trained_models/qwen_fusion_sft_conflict_aware",
        "trained_models/qwen_rlvf_gen_fixed",
    ])
    args = ap.parse_args()

    out = {"splits": {}, "cluster_robust": {}}
    print(f'{"split":38s}{"rows":>7s}{"questions":>11s}{"structures":>12s}{"replication":>13s}')
    for f in sorted(glob.glob("data/test_*.csv")):
        st = split_stats(f)
        if not st:
            continue
        out["splits"][os.path.basename(f)] = st
        print(f'{os.path.basename(f):38s}{st["rows"]:7d}{st["questions"]:11d}'
              f'{st["unique_structures"]:12d}{st["replication"]:13.1f}x')

    split_csv = "data/test_variant3_mixed.csv"
    print(f"\ncluster-robust vs naive intervals on {os.path.basename(split_csv)}")
    for ck in args.checkpoints:
        pred = f"{ck}/predictions/qwen_variant3_mixed_predictions.csv"
        if not os.path.exists(pred):
            continue
        r = cluster_bootstrap(pred, split_csv)
        if not r:
            continue
        out["cluster_robust"][os.path.basename(ck)] = r
        print(f'  {os.path.basename(ck):34s} acc={r["accuracy"]:.4f}  '
              f'clusters={r["clusters"]:4d}  cluster 95% CI={r["ci95_cluster"]}  '
              f'naive={r["ci95_naive"]}  width x{r["width_ratio"]}')

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
